spring.application.name=SmartCityGuide

# MySQL Database Configuration
spring.datasource.url=jdbc:mysql://localhost:3306/smartcityguide
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# Google OAuth2 Login
spring.security.oauth2.client.registration.google.client-id=403754501474-uc3d071eos7js88blnj3ndigd0ihvio5.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret=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
spring.security.oauth2.client.registration.google.scope=email,profile

# Optional
spring.security.oauth2.client.registration.google.redirect-uri={baseUrl}/login/oauth2/code/{registrationId}
gemini.api.key=AQ.Ab8RN6IYjErMxg6GZOnMXq2nu6phXLqz1opMElslJvNFvBVKaA
gemini.api.url=https://generativelanguage.googleapis.com/v1beta/models/gemini-3.5-flash-lite:generateContent
