package com.smartcity.smartcityguide.service.impl;

import com.smartcity.smartcityguide.dto.GroupMemberRequest;
import com.smartcity.smartcityguide.dto.GroupRecommendationRequest;
import com.smartcity.smartcityguide.dto.GroupRecommendationResponse;
import com.smartcity.smartcityguide.service.GroupRecommendationService;
import org.springframework.stereotype.Service;
import com.smartcity.smartcityguide.dto.RecommendationRequest;
import com.smartcity.smartcityguide.dto.RecommendationResponse;
import com.smartcity.smartcityguide.entity.Attraction;
import com.smartcity.smartcityguide.entity.Hotel;
import com.smartcity.smartcityguide.entity.Restaurant;
import com.smartcity.smartcityguide.service.RecommendationService;
import org.springframework.beans.factory.annotation.Autowired;

import java.util.List;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.Map;

@Service
public class GroupRecommendationServiceImpl implements GroupRecommendationService {

    @Autowired
private RecommendationService recommendationService;

    @Override
public GroupRecommendationResponse getGroupRecommendation(GroupRecommendationRequest request) {

    GroupRecommendationResponse response = new GroupRecommendationResponse();

    if (request.getMembers() == null || request.getMembers().isEmpty()) {
        response.setCompatibilityScore(0);
        response.setExplanation("No group members provided.");
        return response;
    }

    int totalMembers = request.getMembers().size();
    int matchedPreferences = 0;

    // Compare every member with the group's common preferences
    String budget = findMostCommonBudget(request);
    String persona = findMostCommonPersona(request);
    String time = findMostCommonTime(request);
    String transport = findMostCommonTransport(request);

    for (int i = 1; i < totalMembers; i++) {

        if (budget.equalsIgnoreCase(request.getMembers().get(i).getPriceRange())) {
            matchedPreferences++;
        }

        if (persona.equalsIgnoreCase(request.getMembers().get(i).getBestFor())) {
            matchedPreferences++;
        }

        if (time.equalsIgnoreCase(request.getMembers().get(i).getTimeAvailable())) {
            matchedPreferences++;
        }

        if (transport.equalsIgnoreCase(request.getMembers().get(i).getTransport())) {
            matchedPreferences++;
        }
    }

    int totalComparisons = (totalMembers - 1) * 4;

    int compatibility =
            totalComparisons == 0
                    ? 100
                    : (matchedPreferences * 100) / totalComparisons;

    response.setCompatibilityScore(compatibility);

    response.setCommonBudget(budget);
    response.setCommonPersona(persona);
    response.setCommonTimeAvailable(time);
    response.setCommonTransport(transport);

    // Create a recommendation request using the first member's preferences
RecommendationRequest recommendationRequest = new RecommendationRequest();

recommendationRequest.setCity(request.getCity());
recommendationRequest.setPriceRange(budget);
recommendationRequest.setBestFor(persona);
recommendationRequest.setTimeAvailable(time);
recommendationRequest.setTransport(transport);
recommendationRequest.setSurpriseMe(request.isSurpriseMe());

// Call existing recommendation engine
RecommendationResponse recommendationResponse =
        recommendationService.getRecommendations(recommendationRequest);

// Copy recommendations into group response
response.setHotels(recommendationResponse.getHotels());
response.setRestaurants(recommendationResponse.getRestaurants());
response.setAttractions(recommendationResponse.getAttractions());
response.setEvents(recommendationResponse.getEvents());

   response.setExplanation(
        "The itinerary was generated by identifying the most common preferences among the group. " +
        "Where preferences differed, the majority choice was selected as a reasonable compromise. " +
        "Selected Budget: " + budget +
        ", Persona: " + persona +
        ", Time Available: " + time +
        ", Transport: " + transport +
        ". Overall Compatibility Score: " + compatibility + "%."
    );

    return response;
}
private String findMostCommon(Map<String, Integer> countMap) {

    int max = countMap.values().stream()
            .max(Integer::compareTo)
            .orElse(0);

    StringBuilder result = new StringBuilder();

    for (Map.Entry<String, Integer> entry : countMap.entrySet()) {

        if (entry.getValue() == max) {

            if (result.length() > 0) {
                result.append(", ");
            }

            result.append(entry.getKey());
        }
    }

    if (result.toString().contains(",")) {
        return "Mixed (" + result + ")";
    }

    return result.toString();
}

private String findMostCommonBudget(GroupRecommendationRequest request) {

    Map<String, Integer> countMap = new HashMap<>();

    for (GroupMemberRequest member : request.getMembers()) {
        countMap.put(
                member.getPriceRange(),
                countMap.getOrDefault(member.getPriceRange(), 0) + 1
        );
    }

    return findMostCommon(countMap);
}

private String findMostCommonPersona(GroupRecommendationRequest request) {

    Map<String, Integer> countMap = new HashMap<>();

    for (GroupMemberRequest member : request.getMembers()) {
        countMap.put(
                member.getBestFor(),
                countMap.getOrDefault(member.getBestFor(), 0) + 1);
    }

    return findMostCommon(countMap);
}

private String findMostCommonTime(GroupRecommendationRequest request) {

    Map<String, Integer> countMap = new HashMap<>();

    for (GroupMemberRequest member : request.getMembers()) {
        countMap.put(
                member.getTimeAvailable(),
                countMap.getOrDefault(member.getTimeAvailable(), 0) + 1);
    }

    return findMostCommon(countMap);
}

private String findMostCommonTransport(GroupRecommendationRequest request) {

    Map<String, Integer> countMap = new HashMap<>();

    for (GroupMemberRequest member : request.getMembers()) {
        countMap.put(
                member.getTransport(),
                countMap.getOrDefault(member.getTransport(), 0) + 1);
    }

    return findMostCommon(countMap);
}

}